name: Build and Release

on:
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      nightly:
        description: "Trigger a nightly build"
        required: false
        default: false
        type: boolean

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      proceed: ${{ steps.check.outputs.proceed }}
      nightly_tag: ${{ steps.set_nightly.outputs.nightly_tag }}
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes since last nightly tag
        id: check
        run: |
          PROCEED="true"

          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "Schedule trigger: Checking changes..."

            LATEST_NIGHTLY_TAG=$(git tag --sort=-creatordate --list '*-nightly.*' | head -n 1)

            if [[ -n "$LATEST_NIGHTLY_TAG" ]]; then
              echo "Latest nightly tag found: $LATEST_NIGHTLY_TAG"
              LATEST_NIGHTLY_COMMIT=$(git rev-list -n 1 "$LATEST_NIGHTLY_TAG" 2>/dev/null)
              CURRENT_HEAD_COMMIT=$(git rev-parse HEAD)

              echo "Commit for tag $LATEST_NIGHTLY_TAG: $LATEST_NIGHTLY_COMMIT"
              echo "Current HEAD commit: $CURRENT_HEAD_COMMIT"

              if [[ "$LATEST_NIGHTLY_COMMIT" == "$CURRENT_HEAD_COMMIT" ]]; then
                echo "No code changes detected since the last nightly release ($LATEST_NIGHTLY_TAG)."
                PROCEED="false"
              else
                echo "Code changes detected since $LATEST_NIGHTLY_TAG. Proceeding with build."
              fi
            else
              echo "No previous nightly tag found. Proceeding with build."
            fi
          else
            echo "Manual trigger ('${{ github.event_name }}'). Proceeding with build."
          fi

          echo "proceed=$PROCEED" >> $GITHUB_OUTPUT

      - name: Set nightly version suffix
        id: set_nightly
        if: github.event_name == 'schedule' || github.event.inputs.nightly
        run: |
          DATE=$(date +%Y%m%d)
          echo "nightly_tag=nightly.$DATE" >> "$GITHUB_OUTPUT"

  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            artifact_name: mandolin-linux-x86_64.vsix
          - os: ubuntu-22.04-arm
            artifact_name: mandolin-linux-aarch64.vsix
          - os: macos-latest
            artifact_name: mandolin-macos-aarch64.vsix
          - os: windows-latest
            artifact_name: mandolin-windows-x86_64.vsix
      fail-fast: false

    needs: check
    if: ${{ needs.check.outputs.proceed == 'true' }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install foreman dependencies
        uses: Roblox/setup-foreman@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow-external-github-orgs: true

      - name: Copy lute executable
        shell: bash
        run: |
          mkdir -p ./bin
          cp $(type -p lute) ./bin/lute
          if [ "${{ matrix.os }}" != "windows-latest" ]; then
            chmod +x ./bin/lute
          fi

      - name: Install node dependencies
        run: npm install

      - name: Build Mandolin
        id: build_mandolin
        run: npx vsce package -o ./mandolin.vsix

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./mandolin.vsix
          name: ${{ matrix.artifact_name }}

  release:
    needs: [check, build]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - run: |
          mkdir release
          for dir in ./artifacts/*; do
            base_name=$(basename "$dir")
            cp artifacts/"${base_name}"/mandolin.vsix release/"${base_name}"
            # chmod 755 "$dir"/* # Artifacts don't preserve permissions, so re-add them.
            # zip -rj release/"${base_name}" "$dir"/*
          done

      - name: Create Nightly Tag
        id: tag_step
        if: needs.check.outputs.nightly_tag
        shell: bash
        run: |
          echo "tag=-${{ needs.check.outputs.nightly_tag }}" >> $GITHUB_OUTPUT

      - name: Create Release Tag
        id: tag_release
        shell: bash
        run: |
          NIGHTLY_TAG=${{ steps.tag_step.outputs.tag }}
          RELEASE_TAG="0.0.1$NIGHTLY_TAG"
          echo "tag=$RELEASE_TAG" >> $GITHUB_OUTPUT

      - name: Check workspace
        run: |
          ls -laRp .

      - name: Create Draft Release
        uses: luau-lang/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_release.outputs.tag }}
          name: ${{ steps.tag_release.outputs.tag }}
          draft: true
          prerelease: true
          files: ./release/*.vsix

      # - name: Wait for Tag Creation in GitHub
      #   run: sleep 5

      # - name: Publish Release
      #   run: gh release edit "${{ steps.tag_release.outputs.tag }}" --draft=false
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
